apiVersion: networking.tanzu.vmware.com/v1alpha1
kind: egressPoint
name: spring-metal-ext-services
spec:
  targets:
  - hosts:
    - genai-proxy.sys.tas.vmtanzu.com
    port:
      number: 8443
      protocol: HTTPS