apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: private-chat-CHANGE_ME
  namespace: default
spec:
  alias: ai-chat
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: private-chat
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: CHANGE_ME

---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: private-embed-CHANGE_ME
  namespace: default
spec:
  alias: ai-embed
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: private-embeddings
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: CHANGE_ME
