apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
<<<<<<< HEAD:.tanzu/config/genai-service-binding.yml
  name: genai-chat-spring-metal-openso
=======
  name: genai-chat-CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/genai-service-binding.yml
  namespace: default
spec:
  alias: ai-chat
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: genai-chat
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
<<<<<<< HEAD:.tanzu/config/genai-service-binding.yml
    name: spring-metal-openso
=======
    name: CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/genai-service-binding.yml

---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
<<<<<<< HEAD:.tanzu/config/genai-service-binding.yml
  name: genai-embed-spring-metal-openso
=======
  name: genai-embed-CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/genai-service-binding.yml
  namespace: default
spec:
  alias: ai-embed
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: genai-embed
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
<<<<<<< HEAD:.tanzu/config/genai-service-binding.yml
    name: spring-metal-openso
=======
    name: CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/genai-service-binding.yml
