apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
<<<<<<< HEAD:.tanzu/config/postgres-service-binding.yml
  name: pgvector-spring-metal-openso
=======
  name: pgvector-CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/postgres-service-binding.yml
  namespace: default
spec:
  alias: db
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: pgvector
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
<<<<<<< HEAD:.tanzu/config/postgres-service-binding.yml
    name: spring-metal-openso
=======
    name: CHANGE_ME
>>>>>>> main:runtime-configs/tpk8s/tanzu-changeme/postgres-service-binding.yml
