apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan
metadata:
  name: platform-config
spec:
  registry: openso
  buildpacks:
    builder: "paketobuildpacks/builder-jammy-base"
  postBuildSteps:
  - name: apply-spring-boot-conventions
    namedTask: tanzu-spring-boot
  runtimes:
  - description: create a carvel package for deploying on kubernetes
    name: kubernetes-carvel-package
    steps:
    - namedtask: tanzu-kubernetes-deployment
    - namedtask: tanzu-kubernetes-carvel-package
#    - name: add-route
#      containerTask:
#        image: openso/add-http-route-task
  - description: create kubernetes yaml files for deploying on kubernetes
    name: kubernetes-plain
    steps:
    - namedTask: tanzu-kubernetes-deployment
  - description: write image to file for use with container runtime (i.e docker run)
    name: container-image
    steps:
    - namedTask: tanzu-container-image

---
#  runtimes:
#  - name: kubernetes-plain
#    steps:
#    - name: kubernetes-deployment
#      namedTask: tanzu-kubernetes-deployment
#  - name: kubernetes-carvel-package
#    description: create a carvel package for deploying on kubernetes
#    steps:
#    - namedtask: tanzu-kubernetes-deployment
#    - namedtask: tanzu-kubernetes-carvel-package
#  - name: container-image
#    description: write image to file for use with container runtime (i.e docker run)
#    steps:
#    - namedtask: tanzu-container-image