---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayRouteConfig
metadata:
  name: spring-metal-route-config
spec:
  openapi:
    generation:
      enabled: false
  routes:
  - predicates:
    - Path=/**
    - Method=GET
    order: 1000
    filters:
    - StripPrefix=0
    tags:
    - ui
  service:
    uri: http://spring-metal-ai-test-15
---
apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGatewayMapping
metadata:
  name: spring-metal-mapping
spec:
  gatewayRef:
    name: spring-metal-gateway
  routeConfigRef:
    name: spring-metal-route-config