---
apiVersion: v1
data:
  database: cG9zdGdyZXM=
  host: dGNwLnRhcy52bXRhbnp1LmNvbQ==
  password: N09LOTQ1UEN3OG4xNjAydnozeWs=
  port: MTAyNQ== # 1025
  provider: dGFzcG9zdGdyZXNxbA==  # tas
  type: cG9zdGdyZXNxbA== # mysql
  username: cGdhZG1pbg==
kind: Secret
metadata:
  name: pgvector-ai-creds
type: servicebinding.io/postgresql

---
apiVersion: services.tanzu.vmware.com/v1alpha1
kind: PreProvisionedService
metadata:
  name: pgvector-service
spec:
  bindingConnectors:
  - name: main
    description: Posgres pgvector service for AI use cases
    type: postgresql
    secretRef: 
      name: pgvector-ai-creds
