apiVersion: build.tanzu.vmware.com/v1
kind: ContainerAppBuildPlan 
metadata:
  name: platform-config 
spec:
  registry: harbor.vmtanzu.com/openso-tbs-apps
  buildpacks:
    builder: "paketobuildpacks/builder-jammy-base" 
  runtimes:
  - name: kubertenes-plain
    steps:
    - name: kubernetes-deployment
      namedTask: tanzu-kubernetes-deployment
  - name: container-image 
    steps:
    - name: container-image
      namedTask: tanzu-container-image