apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Space
metadata:
 name: spring-metal-space
spec:
 template:
   spec:
     profiles:
     - name: spring-ai
 availabilityTargets:
 - name: eu-availibility-target
 - name: us-availibility-target
   replicas: 2
 updateStrategy:
   type: RollingUpdate