apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: CHAT_SERVICE_NAME-APP_NAME
  namespace: default
spec:
  alias: CHAT_SERVICE_NAME
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: CHAT_SERVICE_NAME
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: APP_NAME

---
apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: EMBEDDINGS_SERVICE_NAME-APP_NAME
  namespace: default
spec:
  alias: EMBEDDINGS_SERVICE_NAME
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: EMBEDDINGS_SERVICE_NAME
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: APP_NAME
