apiVersion: v1
data:
  uri: CHAT_API_URL
  api-key: CHAT_API_KEY
  model-name: CHAT_MODEL_NAME
  model-capabilities: CHAT_MODEL_CAPABILITIES
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: CHAT_SERVICE_NAME-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: CHAT_SERVICE_NAME
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: CHAT_SERVICE_NAME-creds
---
apiVersion: v1
data:
  uri: EMBED_API_URL
  api-key: EMBED_API_KEY
  model-name: EMBED_MODEL_NAME
  model-capabilities: EMBED_MODEL_CAPABILITIES
  provider: dGFuenU= # tanzu
  type: Z2VuYWk=  # genai
kind: Secret
metadata:
  name: EMBEDDINGS_SERVICE_NAME-creds
type: servicebinding.io/ai

---
apiVersion: services.tanzu.vmware.com/v1
kind: PreProvisionedService
metadata:
  name: EMBEDDINGS_SERVICE_NAME
spec:
  bindingConnectors:
  - name: main
    description: Gen AI credentials
    type: genai
    secretRef:
      name: EMBEDDINGS_SERVICE_NAME-creds
