apiVersion: networking.tanzu.vmware.com/v1alpha1
kind: DomainBinding
metadata:
  name: TPK8S_SUB_DOMAIN-domain
  namespace: default
spec:
  autoAssign:
    port: false
    subdomainOf: ""
  domain: TPK8S_SUB_DOMAIN.TPK8S_DOMAIN
  entrypoint: main
  http: {}
  port: 80
---

apiVersion: networking.tanzu.vmware.com/v1alpha1
kind: EgressPoint
metadata:
  name: ext-services
  namespace: default
spec:
  targets:
  - hosts:
    - tcp.TPCF_DOMAIN
    port:
      number: EGRESS_TCP_PORT
      protocol: TCP
  - hosts:
    - genai-proxy.sys.TPCF_DOMAIN
    port:
      number: 443
      protocol: HTTPS
