apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: PGVECTOR_SERVICE_NAME-APP_NAME
  namespace: default
spec:
  alias: PGVECTOR_SERVICE_NAME
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: PGVECTOR_SERVICE_NAME
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: APP_NAME
