apiVersion: services.tanzu.vmware.com/v1
kind: ServiceBinding
metadata:
  name: gitops-pgvector-spring-metal
  namespace: default
spec:
  alias: db
  serviceRef:
    apiGroup: services.tanzu.vmware.com
    connectorName: main
    kind: PreProvisionedService
    name: gitops-db-vector
  targetRef:
    apiGroup: apps.tanzu.vmware.com
    kind: ContainerApp
    name: spring-metal
