name: Deploy to CF
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "gitops"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt update
          sudo apt install cf8-cli
          sudo apt install openjdk-17-jdk openjdk-17-jre
          sudo update-java-alternatives --set /usr/lib/jvm/java-1.17.0-openjdk-amd64
          export JAVA_HOME=/usr/lib/jvm/java-1.17.0-openjdk-amd64

      - name: Connect to CF API
        env:
          CF_API: ${{ vars.CF_API_ENDPOINT }}
          CF_ORG: ${{ vars.CF_ORG }}
          CF_SPACE: ${{ vars.CF_SPACE }}
        run: |
          cf api $CF_API --skip-ssl-validation
          cf auth admin ${{ secrets.CF_API_TOKEN }}
          cf target -o $CF_ORG -s $CF_SPACE

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-1.17.0-openjdk-amd64  
          mvn clean package -DskipTests

      - name: Deploy
        env:
          APP_NAME: ${{vars.APP_NAME}}
        run: |
          cf push $APP_NAME -f runtime-configs/tpcf/manifest.yml --no-start
          
      - name: Bind
        env:
          APP_NAME: ${{vars.APP_NAME}}
          PGVECTOR_SERVICE_NAME: ${{vars.PGVECTOR_SERVICE_NAME}}
          CHAT_SERVICE_NAME: ${{vars.CHAT_SERVICE_NAME}}
          EMBEDDINGS_SERVICE_NAME: ${{vars.EMBEDDINGS_SERVICE_NAME}}
        run: |
          cf bind-service $APP_NAME $PGVECTOR_SERVICE_NAME
          cf bind-service $APP_NAME $CHAT_SERVICE_NAME
          cf bind-service $APP_NAME $EMBEDDINGS_SERVICE_NAME
      
      - name: Run
        env:
          APP_NAME: ${{vars.APP_NAME}}
        run: |
          cf start $APP_NAME

          
      - run: echo "🍏 This job's status is ${{ job.status }}."
